services:
  yetipredict-nodejs:
    container_name: yetipredict-nodejs
    build:
      context: ./
      dockerfile: ./docker/web/Dockerfile
      network: host
    restart: unless-stopped
    ports:
      - "3829:80"
    depends_on:
      - yetipredict-mongo
  yetipredict-mongo:
    container_name: yetipredict-mongo
    image: mongo:4
    command: mongod --port 27017 --bind_ip 0.0.0.0
    restart: unless-stopped
    volumes:
      - /data/db/yetipredict_mongo:/data/db
    expose:
      - "27017"
