version: "3"
services:
  yetipredict-nodejs:
    container_name: yetipredict-nodejs
    build:
        context: ./
        dockerfile: ./docker/web/Dockerfile
    restart: unless-stopped
    ports:
      - "3829:80"
    depends_on:
      - yetipredict-mongo
  yetipredict-mongo:
    container_name: yetipredict-mongo
    image: webhippie/mongodb:latest
    #image: unguiculus/mongodb-install:0.8
    command: mongod --port 27017 --bind_ip 0.0.0.0
    restart: unless-stopped
    volumes:
      - /data/db/yetipredict_mongo:/data/db
    expose:
      - '27017'
#  yetipredict_mongo:
#    container_name: yetipredict_mongo
#    image: mongo
#  command: mongod --port 27123 --bind_ip 0.0.0.0
#    restart: unless-stopped
#    volumes:
#      - /data/db/yetipredict_mongo:/data/db
#    ports:
#      - '27123:27123'
#  yetipredict_mongo:
#    container_name: yetipredict_mongo
#    build:
#        context: ./
#        dockerfile: ./docker/db/Dockerfile
#    command: mongod --port 27123 --bind_ip 0.0.0.0
#    restart: unless-stopped
#    volumes:
#      - /data/db/yetipredict_mongo:/data/db
#    ports:
#      - '27123:27123'
#
