version: "3"
services:
  yetipredict_nodejs:
    container_name: yetipredict_nodejs
    build:
        context: ./
        dockerfile: ./docker/web/Dockerfile
    restart: unless-stopped
    ports:
      - "3829:3829"
    depends_on:
      - yetipredict_mongo
#  yetipredict_mongo:
#    container_name: yetipredict_mongo
#    image: webhippie/mongodb
#    command: mongod --port 27123 --bind_ip 0.0.0.0
#    restart: unless-stopped
#    volumes:
#      - /data/db/yetipredict_mongo:/data/db
#    ports:
#      - '27123:27123'
#  yetipredict_mongo:
#    container_name: yetipredict_mongo
#    image: mongo
#    command: mongod --port 27123 --bind_ip 0.0.0.0
#    restart: unless-stopped
#    volumes:
#      - /data/db/yetipredict_mongo:/data/db
#    ports:
#      - '27123:27123'
  yetipredict_mongo:
    container_name: yetipredict_mongo
    build:
        context: ./
        dockerfile: ./docker/db/Dockerfile
    command: mongod --port 27123 --bind_ip 0.0.0.0
    restart: unless-stopped
    volumes:
      - /data/db/yetipredict_mongo:/data/db
    ports:
      - '27123:27123'

